# Generated by Django 6.0 on 2025-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0004_timeslot_remove_course_day_of_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to="accounts.profile"
            ),
        ),
    ]
