# Generated by Django 5.2.8 on 2025-12-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_units',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
